// geographicalNames.js

export const geographicalNames = [
    // Countries (500 names)
    "AFGHANISTAN", "ALBANIA", "ALGERIA", "ANDORRA", "ANGOLA", "ANTIGUAANDBARBUDA", "ARGENTINA", "ARMENIA", "AUSTRALIA", "AUSTRIA",
    "AZERBAIJAN", "BAHAMAS", "BAHRAIN", "BANGLADESH", "BARBADOS", "BELARUS", "BELGIUM", "BELIZE", "BENIN", "BHUTAN",
    "BOLIVIA", "BOSNIAANDHERZEGOVINA", "BOTSWANA", "BRAZIL", "BRUNEI", "BULGARIA", "BURKINAFASO", "BURUNDI", "CAMBODIA", "CAMEROON",
    "CANADA", "CAPEVERDE", "CENTRALAFRICANREPUBLIC", "CHAD", "CHILE", "CHINA", "COLOMBIA", "COMOROS", "CONGO", "COSTARICA",
    "CROATIA", "CUBA", "CYPRUS", "CZECHREPUBLIC", "DEMOCRATICREPUBLICOFCONGO", "DENMARK", "DJIBOUTI", "DOMINICA", "DOMINICANREPUBLIC", "EASTTIMOR",
    "ECUADOR", "EGYPT", "ELSALVADOR", "EQUATORIALGUINEA", "ERITREA", "ESTONIA", "ESWATINI", "ETHIOPIA", "FIJI", "FINLAND",
    "FRANCE", "GABON", "GAMBIA", "GEORGIA", "GERMANY", "GHANA", "GREECE", "GRENADA", "GUATEMALA", "GUINEA",
    "GUINEABISSAU", "GUYANA", "HAITI", "HONDURAS", "HUNGARY", "ICELAND", "INDIA", "INDONESIA", "IRAN", "IRAQ",
    "IRELAND", "ISRAEL", "ITALY", "IVORYCOAST", "JAMAICA", "JAPAN", "JORDAN", "KAZAKHSTAN", "KENYA", "KIRIBATI",
    "KUWAIT", "KYRGYZSTAN", "LAOS", "LATVIA", "LEBANON", "LESOTHO", "LIBERIA", "LIBYA", "LIECHTENSTEIN", "LITHUANIA",
    "LUXEMBOURG", "MADAGASCAR", "MALAWI", "MALAYSIA", "MALDIVES", "MALI", "MALTA", "MARSHALLISLANDS", "MAURITANIA", "MAURITIUS",
    "MEXICO", "MICRONESIA", "MOLDOVA", "MONACO", "MONGOLIA", "MONTENEGRO", "MOROCCO", "MOZAMBIQUE", "MYANMAR", "NAMIBIA",
    "NAURU", "NEPAL", "NETHERLANDS", "NEWZEALAND", "NICARAGUA", "NIGER", "NIGERIA", "NORTHKOREA", "NORTHMACEDONIA", "NORWAY",
    "OMAN", "PAKISTAN", "PALAU", "PALESTINE", "PANAMA", "PAPUANEWGUINEA", "PARAGUAY", "PERU", "PHILIPPINES", "POLAND",
    "PORTUGAL", "QATAR", "ROMANIA", "RUSSIA", "RWANDA", "SAINTKILTSANDNEVIS", "SAINTLUCIA", "SAINTVINCENTANDTHEGRENADINES", "SAMOA", "SANMARINO",
    "SAOTOMEANDPRINCIPE", "SAUDIARABIA", "SENEGAL", "SERBIA", "SEYCHELLES", "SIERRALEONE", "SINGAPORE", "SLOVAKIA", "SLOVENIA", "SOLOMONISLANDS",
    "SOMALIA", "SOUTHAFRICA", "SOUTHKOREA", "SOUTHSUDAN", "SPAIN", "SRILANKA", "SUDAN", "SURINAME", "SWEDEN", "SWITZERLAND",
    "SYRIA", "TAIWAN", "TAJIKISTAN", "TANZANIA", "THAILAND", "TOGO", "TONGA", "TRINIDADANDTOBAGO", "TUNISIA", "TURKEY",
    "TURKMENISTAN", "TUVALU", "UGANDA", "UKRAINE", "UNITEDARABEMIRATES", "UNITEDKINGDOM", "UNITEDSTATES", "URUGUAY", "UZBEKISTAN", "VANUATU",
    "VATICANCITY", "VENEZUELA", "VIETNAM", "YEMEN", "ZAMBIA", "ZIMBABWE",
    
    // ... (Add 380 more country names or related terms)
  
    // Major Cities and Regions (500 names)
    "TOKYO", "DELHI", "SHANGHAI", "SAOPAULLO", "MEXICOCITY", "CAIRO", "MUMBAI", "BEIJING", "DHAKA", "OSAKA",
    "NEWYORK", "KARACHI", "BUENOSAIRES", "CHONGQING", "ISTANBUL", "KOLKATA", "MANILA", "LAGOS", "RIODEJANEIRO", "TIANJIN",
    "KINSHASA", "GUANGZHOU", "LOSANGELES", "MOSCOW", "SHENZHEN", "LAHORE", "BANGALORE", "PARIS", "BOGOTA", "JAKARTA",
    "CHENNAI", "LIMA", "BANGKOK", "SEOUL", "NAGOYA", "HYDERABAD", "LONDON", "TEHRAN", "CHICAGO", "CHENGDU",
    "NANJING", "WUHAN", "HOCHIMINHCITY", "AHMEDABAD", "KUALALUMPUR", "HONGKONG", "DONGGUAN", "HANGZHOU", "FOSHAN", "SHENYANG",
    "RIYADH", "BAGHDAD", "SANTIAGO", "SURAT", "MADRID", "SUZHOU", "PUNE", "HARBIN", "HOUSTON", "DALLAS",
    "TORONTO", "MIAMI", "SINGAPORE", "PHILADELPHIA", "ATLANTA", "FUKUOKA", "KHARTOUM", "BARCELONA", "JOHANNESBURG", "BERLIN",
    "AMSTERDAM", "ATHENS", "AUCKLAND", "BELGRADE", "BERN", "BOSTON", "BRASILIA", "BRUSSELS", "BUCHAREST", "BUDAPEST",
    "CAPETOWN", "COPENHAGEN", "DAKAR", "DAMASCUS", "DENVER", "DETROIT", "DUBAI", "DUBLIN", "EDINBURGH", "GENEVA",
    "GLASGOW", "GOTHENBURG", "HAMBURG", "HANOI", "HAVANA", "HELSINKI", "INDIANAPOLIS", "ISLAMABAD", "JERUSALEM", "KABUL",
    
    // ... (Add 400 more city and region names)
  
    // Geographical Features (500 names)
    "AMAZON", "ANDES", "ANTARCTICA", "ARCTIC", "ATACAMA", "ATLANTIC", "BAIKAL", "BALKAN", "BAYOFBENGAL", "BLACKSEA",
    "CASPIAN", "CAUCASUS", "CONGO", "DANUBE", "DEADSEA", "EVEREST", "FUJI", "GANGES", "GOBI", "GREATLAKES",
    "HIMALAYAS", "INDIANOCEAN", "KILIMANJARO", "MEDITERRANEAN", "MISSISSIPPI", "NILE", "NORTHSEA", "PACIFICOCEAN", "PAMIR", "REDSEA",
    "ROCKIES", "SAHARA", "SIBERIA", "TASMANIA", "THARDESERT", "TIBET", "URAL", "VICTORIA", "VOLGA", "YELLOWSTONE",
    "ALPES", "APPALACHIAN", "ARABIANSEA", "ATACAMA", "BERING", "BLACKFOREST", "CARPATHIAN", "CHESAPEAKE", "CORDILLERA", "DOLOMITES",
    "GALAPAGOS", "GRANDCANYON", "GREATBARRIERREEF", "GREENBELT", "JUNGFRAU", "KALAHARI", "LAKETITICACA", "MALDIVES", "MATTERHORN", "OKAVANGO",
    "OUTBACK", "PANTANAL", "PATAGONIA", "PHUKET", "POTALA", "RAINIER", "SERENGETI", "SINAI", "STONEHENGE", "SUEZ",
    "SUNDARBANS", "TAURUS", "TEIDE", "ZAMBEZI", "ACONCAGUA", "ADRIATIC", "AEGEAN", "ARAL", "ATLAS", "BAFFIN",
    "BAIKALLAKE", "BALATON", "BALEARIC", "BARBADOS", "BARENTSEA", "BASSROCK", "BAYOFBISCAY", "BEAUFORT", "BELIZE", "BERMUDA",
    
    // ... (Add 450 more geographical feature names)
  ];
